/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_comments` (
  `comment_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `comment_post_ID` bigint(20) unsigned NOT NULL DEFAULT 0,
  `comment_author` tinytext NOT NULL,
  `comment_author_email` varchar(100) NOT NULL DEFAULT '',
  `comment_author_url` varchar(200) NOT NULL DEFAULT '',
  `comment_author_IP` varchar(100) NOT NULL DEFAULT '',
  `comment_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_content` text NOT NULL,
  `comment_karma` int(11) NOT NULL DEFAULT 0,
  `comment_approved` varchar(20) NOT NULL DEFAULT '1',
  `comment_agent` varchar(255) NOT NULL DEFAULT '',
  `comment_type` varchar(20) NOT NULL DEFAULT 'comment',
  `comment_parent` bigint(20) unsigned NOT NULL DEFAULT 0,
  `user_id` bigint(20) unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`comment_ID`),
  KEY `comment_post_ID` (`comment_post_ID`),
  KEY `comment_approved_date_gmt` (`comment_approved`,`comment_date_gmt`),
  KEY `comment_date_gmt` (`comment_date_gmt`),
  KEY `comment_parent` (`comment_parent`),
  KEY `comment_author_email` (`comment_author_email`(10)),
  KEY `woo_idx_comment_type` (`comment_type`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (1,1,'A WordPress Commenter','wapuu@wordpress.example','https://wordpress.org/','','2024-06-26 19:46:13','2024-06-26 19:46:13','Hi, this is a comment.\nTo get started with moderating, editing, and deleting comments, please visit the Comments screen in the dashboard.\nCommenter avatars come from <a href=\"https://en.gravatar.com/\">Gravatar</a>.',0,'1','','comment',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (2,83,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-06-27 01:30:10','2024-06-26 20:00:10','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (3,83,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-06-27 01:30:15','2024-06-26 20:00:15','PhonePe Payment Solutions: Payment Request Failed \n error message: Key not found for the merchant',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (4,83,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-06-27 01:30:15','2024-06-26 20:00:15','Order status changed from Pending payment to Failed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (5,83,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-06-27 01:30:16','2024-06-26 20:00:16','PhonePe Payment Solutions: Payment Transaction Failed - merchant transaction id: ',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (6,83,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-06-28 13:11:03','2024-06-28 07:41:03','Payment to be made upon delivery. Order status changed from Failed to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (7,210,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-06-28 13:59:56','2024-06-28 08:29:56','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (8,210,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-06-28 13:59:56','2024-06-28 08:29:56','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (9,210,'Sparklus lamps','sparkluslamps@gmail.com','','','2024-06-28 14:00:40','2024-06-28 08:30:40','Order details manually sent to customer.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (10,289,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-06-29 13:21:43','2024-06-29 07:51:43','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (11,289,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-06-29 13:21:44','2024-06-29 07:51:44','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (12,289,'Sparklus lamps','sparkluslamps@gmail.com','','','2024-06-29 15:06:30','2024-06-29 09:36:30','Order details manually sent to customer.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (13,338,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 04:25:43','2024-06-30 22:55:43','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (14,338,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 04:25:43','2024-06-30 22:55:43','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (15,339,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 12:55:24','2024-07-01 07:25:24','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (16,339,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 12:55:24','2024-07-01 07:25:24','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (17,340,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 13:03:28','2024-07-01 07:33:28','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (18,340,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 13:03:28','2024-07-01 07:33:28','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (19,341,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 13:06:43','2024-07-01 07:36:43','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (20,341,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 13:06:43','2024-07-01 07:36:43','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (21,342,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 13:49:16','2024-07-01 08:19:16','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (22,342,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 13:49:16','2024-07-01 08:19:16','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (23,343,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 14:12:37','2024-07-01 08:42:37','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (24,343,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 14:12:37','2024-07-01 08:42:37','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (25,347,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 23:57:41','2024-07-01 18:27:41','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (26,347,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-01 23:57:41','2024-07-01 18:27:41','Payment to be made upon delivery. Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (33,572,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-05 22:07:45','2024-07-05 16:37:45','Order status changed from Draft to Pending payment.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (34,572,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-05 22:07:51','2024-07-05 16:37:51','PhonePe Payment Solutions: Payment Request Failed \n error message: Key not found for the merchant',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (35,572,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-05 22:07:51','2024-07-05 16:37:51','Order status changed from Pending payment to Failed.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (36,572,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-05 22:07:52','2024-07-05 16:37:52','PhonePe Payment Solutions: Payment Transaction Failed - merchant transaction id: ',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (37,658,'WooCommerce','woocommerce@sparkluslamps.com','','','2024-07-15 12:06:36','2024-07-15 06:36:36','Order status changed from Pending payment to Processing.',0,'1','WooCommerce','order_note',0,0);
INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES (38,658,'Sparklus lamps','sparkluslamps@gmail.com','','','2024-07-15 12:07:25','2024-07-15 06:37:25','Order status changed from Processing to Cancelled.',0,'1','WooCommerce','order_note',0,0);
