/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_wc_order_addresses` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `order_id` bigint(20) unsigned NOT NULL,
  `address_type` varchar(20) DEFAULT NULL,
  `first_name` text DEFAULT NULL,
  `last_name` text DEFAULT NULL,
  `company` text DEFAULT NULL,
  `address_1` text DEFAULT NULL,
  `address_2` text DEFAULT NULL,
  `city` text DEFAULT NULL,
  `state` text DEFAULT NULL,
  `postcode` text DEFAULT NULL,
  `country` text DEFAULT NULL,
  `email` varchar(320) DEFAULT NULL,
  `phone` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `address_type_order_id` (`address_type`,`order_id`),
  KEY `order_id` (`order_id`),
  KEY `email` (`email`(191)),
  KEY `phone` (`phone`)
) ENGINE=InnoDB AUTO_INCREMENT=1085 DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (1,83,'billing','Ayush ','Tandon',NULL,'48 tandon bara biharipur',NULL,'Bareilly','UP','243003','IN','sparkluslamps@gmail.com','9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (2,83,'shipping','Ayush ','Tandon',NULL,'48 tandon bara biharipur',NULL,'Bareilly','UP','243003','IN',NULL,'9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (5,210,'billing','Ayush','Tandon',NULL,'48 tandon bara biharipur',NULL,'Bareilly','UP','243003','IN','sparkluslamps@gmail.com','9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (6,210,'shipping','Ayush','Tandon',NULL,'48 tandon bara biharipur',NULL,'Bareilly','UP','243003','IN',NULL,'9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (15,289,'billing','Ayush','Tandon',NULL,'48 tandon bara biharipur',NULL,'Bareilly','UP','243003','IN','sparkluslamps@gmail.com','9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (16,289,'shipping','Ayush','Tandon',NULL,'48 tandon bara biharipur',NULL,'Bareilly','UP','243003','IN',NULL,'9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (19,338,'billing','Ayush','Tandon',NULL,'48 TANDON BARA,BIHARIPUR',NULL,'Bareilly','UP','243003','IN','ayushjtandon@gmail.com','09548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (20,338,'shipping','Ayush','Tandon',NULL,'48 TANDON BARA,BIHARIPUR',NULL,'Bareilly','UP','243003','IN',NULL,'09548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (21,339,'billing','Ayush','Tandon',NULL,'48 Tandon Bara bihraipur',NULL,'Bareilly','UP','243003','IN','ayush2@gmail.com','9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (22,339,'shipping','Ayush','Tandon',NULL,'48 Tandon Bara bihraipur',NULL,'Bareilly','UP','243003','IN',NULL,'9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (23,340,'billing','Ayush','Tandon',NULL,'48 Tandon',NULL,'Bareilly','UP','243003','IN','ayush3@gmail.com','9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (24,340,'shipping','Ayush','Tandon',NULL,'48 Tandon',NULL,'Bareilly','UP','243003','IN',NULL,'9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (25,341,'billing','Ayush','Tandon',NULL,'48 Tandon ',NULL,'Bareilly','UP','243003','IN','ayush3@gmail.com','9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (26,341,'shipping','Ayush','Tandon',NULL,'48 Tandon ',NULL,'Bareilly','UP','243003','IN',NULL,'9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (27,342,'billing','Ayush ','Tandon',NULL,'48',NULL,'Bareilly','UP','243003','IN','ayush4@gmail.com','9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (28,342,'shipping','Ayush ','Tandon',NULL,'48',NULL,'Bareilly','UP','243003','IN',NULL,'9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (29,343,'billing','Ayush','Tandon',NULL,'48 TANDON BARA,BIHARIPUR',NULL,'Bareilly','UP','243003','IN','er.vaibhavkhanna@gmail.com','09548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (30,343,'shipping','Ayush','Tandon',NULL,'48 TANDON BARA,BIHARIPUR',NULL,'Bareilly','UP','243003','IN',NULL,'09548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (37,347,'billing','Rishabh ','Chawla ',NULL,'Janakpuri ',NULL,'Bareilly ','UP','243122','IN','rishabh123@gmail.com',NULL);
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (38,347,'shipping','Rishabh ','Chawla ',NULL,'Janakpuri ',NULL,'Bareilly ','UP','243122','IN',NULL,NULL);
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (41,364,'billing','Hello','World',NULL,'bareilly','48 tandon','Bareilly','UP','243003','IN','helloworld@gmail.com','123789456');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (42,364,'shipping','Hello','World',NULL,'bareilly','48 tandon','Bareilly','UP','243003','IN',NULL,'123789456');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (45,435,'billing','Ayush','Tandon',NULL,'48 TANDON BARA,BIHARIPUR',NULL,'Bareilly','UP','243003','IN','ayusht060319@gmail.com','09548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (46,435,'shipping','Ayush','Tandon',NULL,'48 TANDON BARA,BIHARIPUR',NULL,'Bareilly','UP','243003','IN',NULL,'09548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (51,551,'billing','Hello','knou',NULL,'bboboubbb',NULL,'Bareilly','UP','243003','IN','test@gmail.com','9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (52,551,'shipping','Hello','knou',NULL,'bboboubbb',NULL,'Bareilly','UP','243003','IN',NULL,'9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (55,572,'billing','Sanjay','Tandon',NULL,'48 Tandon Bara Beharipur Bareilly, India','Beharipur','Bareilly','UP','243003','IN','sanjaytandon.2210@gmail.com','06396262842');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (56,572,'shipping','Sanjay','Tandon',NULL,'48 Tandon Bara Beharipur Bareilly, India','Beharipur','Bareilly','UP','243003','IN',NULL,'06396262842');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (63,658,'billing','Testing','Team',NULL,'Test Order','Test Order','Gurgaon','HR','122002','IN','rohitvishwakarma77707@gmail.com','7275977707');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (64,658,'shipping','Testing','Team',NULL,'Test Order','Test Order','Gurgaon','HR','122002','IN',NULL,'7275977707');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (1083,734,'billing','Ayush','Tandon',NULL,'48 tandon bara biharipur',NULL,'Bareilly','UP','243003','IN','sparkluslamps@gmail.com','9548218100');
INSERT INTO `wp_wc_order_addresses` (`id`, `order_id`, `address_type`, `first_name`, `last_name`, `company`, `address_1`, `address_2`, `city`, `state`, `postcode`, `country`, `email`, `phone`) VALUES (1084,734,'shipping',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'9548218100');
